name: Deploy web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make git dirs safe + show config
        shell: bash
        run: |
          set -eux
          git --version
          echo "WS=$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE" || true
          git config --global --add safe.directory /github/workspace || true
          git config --global --add safe.directory '*' || true
          git config --global --list --show-origin || true
          git rev-parse --show-toplevel || true
          git status || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (CI guards)
        env:
          HUSKY: 0
          ADBLOCK: 1
          npm_config_fund: false
          npm_config_audit: false
        run: npm ci --no-audit --no-fund --verbose

      - name: Build (Expo export)
        env:
          CI: true
        run: npx expo export --platform web --output-dir dist

      # NEW: rewrite absolute asset URLs -> relative
      - name: Make asset URLs relative
        shell: bash
        run: |
          set -e
          find dist -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) \
            -exec sed -i 's|/_expo/|./_expo/|g' {} +
          grep -n "./_expo/" dist/index.html || true

      - name: Ensure MSW worker exists
        run: |
          set -eux
          if [ ! -f dist/mockServiceWorker.js ]; then
            for f in web/mockServiceWorker.js public/mockServiceWorker.js; do
              if [ -f "$f" ]; then cp "$f" dist/; fi
            done
          fi

      - name: Add SPA 404.html
        run: |
          [ -f dist/404.html ] || cp dist/index.html dist/404.html

      # NEW: disable Jekyll so /_expo/** is served
      - name: Disable Jekyll (serve _expo/)
        run: echo > dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
