name: Deploy web to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Required by GitHub Pages deploy
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      # If you use submodules, add: submodules: true
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Build static web with Expo
      - name: Export Expo web
        run: npx expo export --platform web --output-dir dist

      # Copy MSW worker + SPA fallback (if they exist)
      - name: Copy MSW worker and 404 fallback
        run: |
          mkdir -p dist
          # MSW worker (try both locations just in case)
          if [ -f public/mockServiceWorker.js ]; then cp public/mockServiceWorker.js dist/mockServiceWorker.js; fi
          if [ -f web/mockServiceWorker.js ]; then cp web/mockServiceWorker.js dist/mockServiceWorker.js; fi
          # SPA 404 fallback
          if [ -f public/404.html ]; then cp public/404.html dist/404.html; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
